### ISSUE TITLE
When schema contains more than one oneOf, a random one will be picked

### ISSUE THREAD

**Issue by birdsarah** [open-contracting/json-schema-random#4]
May be an issue later when we have other forms of formation type (e.g. negotiation) and we want to output a blank schema with everything.

**Comment by birdsarah** [comment]
My feeling of the best way to handle this would be to have an option like "--oneOfInteractive" where if you used it and the parser encountered a oneOf, you were given an interactive option to pick which oneOf object you want to populate.

I think it would be incorrect if it did spit out more than one object from the oneOf, because then it wouldn't be valid by the schema. 

But for open ocntracting use case (which is probably pretty unusual) I could just repeat the process for the different one ofs and then mash it all together.

**Comment by jpmckinney** [comment]
I'm not sure we need to guarantee full coverage of the schema when generating random examples, so closing.
